### ISSUE TITLE
Symfony 5.4 support

### ISSUE THREAD

**Issue by floviolleau** [thomasbeaujean/getter-trait-bundle#2]
Hi,

Is it possible to make it Symfony 5.x support?

Thanks

**Comment by thomasbeaujean** [comment]
Hi,

I did not test the bundle in sf 5.x environment (only 6.x), I will check if there no big drawbacks with a backward compatibility.

**Comment by thomasbeaujean** [comment]
I  did some refactoring on this bundle:
- bundle requires now sf ^5.4 
- autoload services
- some technical refactoring
- add phpunit
- add CI with several version of SF

https://github.com/thomasbeaujean/getter-trait-bundle/actions/runs/5955636402/job/16154702432

So, it should  work with your project.  Please let me know if something is not working correctly.
